#!/usr/bin/env perl 

use strict;
use warnings;
use Data::Uniqid qw/suniqid/;
use String::ShellQuote qw/shell_quote/;

my $cmd = join ' ', shell_quote @ARGV;
my $host = `uname -n`;
chomp $host;
my $id = $host . '_' . suniqid;
my $prop = 'PXEXEC_CMD_' . $id;
system('xprop', '-f', $prop, '8s', '-root', '-set', $prop, $cmd)
	and die "Could not set property on root window using xprop: $!";
my $pid = open my $h, '-|', 'xprop', '-root', '-spy'
	or die "Could not listen to property changes using xprop: $!";
my $res;
while (<$h>) {
	if (/^PXEXEC_RESULT_\Q$id\E\(STRING\)\s*=\s*(.*)$/) {
		$res = $1;
		last;
	}
}
kill 9, $pid;
close($h);
system('xprop', '-root', '-remove', 'PXEXEC_RESULT_' . $id);
die "Did not get result from command." unless $res;
$res = eval $res;
die $res unless $res =~ /\t/;
my ($exitcode, $output) = split "\t", $res, 2;
print $output;
exit $exitcode;
