#!/usr/bin/env perl 
use strict;
use warnings;

open my $h, '-|', 'xprop -root -spy'
	or die "Could not listen to property changes using xprop: $!";
while (<$h>) {
	if (/^PXEXEC_(\w+)\(STRING\)\s*=\s*(.*)$/) {
		my ($id, $cmd) = ($1, eval $2);
		warn "$id: $cmd";
		system('xprop', '-root', '-remove', 'PXEXEC_' . $id);
	}
}

